[project]
name = "scraper"
version = "0.1.0"
description = "Web scraper application using Scrapy"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "Scrapy>=2.11.0",
    "requests>=2.31.0",
    "pydantic>=2.0.0",
    "python-dotenv>=1.0.0",
    "asyncpg>=0.29.0",
    "db",
]
